Template.loading.helpers({
  quote: function(){
    return _.sample(quotes)
  }
});

var quotes = [
  "Patience is a virtue.",
  "Diligence is the mother of good luck.",
  "Whether you think you can, or think you can't--you're right.",
  "Chase the vision, not the money; the money will end up following you.",
  "The value of an idea lies in the using of it.",
  "Make every detail perfect and limit the number of details to perfect.",
  "Don't worry about failure; you only have to be right once.",
  "Nothing works better than just improving your product.",
  "Ideas are commodity. Execution of them is not.",
  "The Earth is just too small and fragile a basket for the human race to keep all its eggs in.",
  "We shall not cease from exploration. And the end of all our exploring will be to arrive where we started and know the place for the first time.",
  "How dare you open a spaceman's helmet on an uncharted planet?!",
  "In the space between chaos and shape there was another chance.",
  "I didn't feel like a giant. I felt very, very small.",
  "I’m coming back in… and it’s the saddest moment of my life.",
  "When I first looked back at the Earth, standing on the Moon, I cried.",
  "There is perhaps no better a demonstration of the folly of human conceits than this distant image of our tiny world.",
  "Contact light.",
  "It’s a fixer-upper of a planet but we could make it work.",
  "I say, this has really been drama of the highest order.",
  "Failure is not an option.",
  "It means nothing to me. I have no opinion about it, and I don’t care.",
  "Go flight.",
  "The only real prison is fear, and the only real freedom is freedom from fear",
  // "If a bullet should enter my brain, let that bullet destroy every closet door.",
  "I, too, sing America... I, too, am America.",
  "If not us, then who? If not now, then when?",
  // "It was civil disobedience that won them their civil rights.",
  // "We have no right to prejudice another in his civil enjoyments because he is of another church.",
  // "For to be free is not merely to cast off one’s chains, but to live in a way that respects and enhances the freedom of others.",
  // "You can chain me, you can torture me, you can even destroy this body, but you will never imprison my mind.",
  // "Those who would give up essential liberty to purchase a little temporary safety deserve neither liberty nor safety.",
  // "All that is necessary for the triumph of evil is for good men to do nothing.",
  "Never doubt that a small group of thoughtful, committed, citizens can change the world.",
  // "When they came for me, there was no one left to speak out.",
  // "You can’t separate peace from freedom because no one can be at peace unless he has his freedom.",
  // "In the End, we will remember not the words of our enemies, but the silence of our friends.",
  // "No one is free when others are oppressed.",
  // "If we don’t believe in freedom of expression for people we despise, we don’t believe in it at all.",
  // "Free speech carries with it some freedom to listen.",
  "Without a struggle, there can be no progress.",
  "The truth shall make you free."
]
